### ISSUE TITLE
Swift Style

### ISSUE THREAD

**Issue by dillidon** [layoutBox/PinLayout#96]
Hi!

Don't you think its better to write

`.margin(left: 10)`

instead of

`.marginLeft(10)`

?

**Comment by lucdion** [comment]
Hi @dillidon, 

1. The first reason why I choose that style is that it works better with Xcode autocomplete. In PinLayout there are so many `margin` methods, that it's faster when you want for example select `marginVertical`, you can simply type `mv` and select the method immediately. Using your proposition you would have to type `marg` then use arrow keys to select the nth margin methods.
 
2. The second reason was that I wanted from the start to be compliant with [Yoga](https://facebook.github.io/yoga/) flexbox implementation, which use this syntax. I wanted that because my other layout project [FlexLayout](https://github.com/layoutBox/FlexLayout) use Yoga.

But your right on one point, your proposition would have been more Swift friendly. Maybe if I have to rewrite the API, I would go with your proposition.

Thanks for your comment.
Luc

**Comment by dillidon** [comment]
Also, instead of: 

`view.pin.below(of: otherView, aligned: .center).marginTop(10)`

I think more swiftly:

`view.pin.below(of: otherView, aligned: center, margin: 10)`

Together with this it would be nice to add a group layout like:

`[view1, view2, view3].pin.all().group(by: .equal, axis: .horizontal).height(100).width(80%)`

**Comment by lucdion** [comment]
@dillidon I'm in the process of designing a way to layout multiple views simultaneously, as your group layout proposition. I may integrate your proposition in my design. If you have any other ideas, thanks for sharing them.

**Comment by dillidon** [comment]
I have not been able to use even 30% of all the features of your framework, but I have already closed all the most difficult moments that I had when I used the Autolayout. Thank you) The only thing I would like to see is the above things.

**Comment by lucdion** [comment]
Thanks for the comment @dillidon. I hope that my group proposition will meet your expectation. I want something really simple for simple cases, but still being able to layout more particular situations.
